workflow:
  rules:
    # Allow being triggered from thr_k8s parent pipeline
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
    # Keep normal behavior for direct pushes / MRs
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

stages:
  - lint
  - build

# KEEP IN MIND! global before_script is not executed when job has its own before_script
before_script:
  # install dependencies
  - npm -v
  - npm ci --legacy-peer-deps

lint:
  stage: lint
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:18
  script:
    - npm run lint

.unit-test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:18
  script:
    - npm test

docker-build:
  stage: build
  # needs: ["unit-test"]
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24-dind
      alias: docker
  variables:
#    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_API_VERSION: "1.43"
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  # By using before_script here we override the global one as we don't need npm ;)
  before_script:
    - echo "$CI_REGISTRY_TOKEN" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
