stages:
  - test
  - build

before_script:
  # upgrade npm
  - npm install -g npm@7.11.1
  - npm -v
  - npm install

variables:
  # This fixes "error during connect: Post http://docker:2375/v1.40/auth: dial tcp: lookup docker on 192.168.65.5:53: no such host"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

## Test

lint-test:
  stage: test
  script:
    - npm run lint

unit-test:
  stage: test
  script:
    - npm test

## Build

app-build:
  stage: build
    needs: ["test"]
    script:
      # fix: "Browserslist: caniuse-lite is outdated"
      - npx browserslist@latest --update-db
      - npm run build

docker-build:
  stage: build
  needs: ["test"]
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:19.03.12
  services:
    - name: docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo $CI_REGISTRY_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
