stages:
  - test
  - build

# KEEP IN MIND! global before_script is not executed when job has its own before_script
before_script:
  # upgrade npm
  - npm install -g npm@7.11.1
  - npm -v
  - npm install

variables:
  # This fixes "error during connect: Post http://docker:2375/v1.40/auth: dial tcp: lookup docker on 192.168.65.5:53: no such host"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

## Test

lint-test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:14.17.3
  script:
    - npm run lint

unit-test:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:14.17.3
  script:
    - npm test

## Build

app-build:
  stage: build
  needs: ["unit-test"]
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:14.17.3
  script:
    # fix: "Browserslist: caniuse-lite is outdated"
    - npx browserslist@latest --update-db
    - npm run build

docker-build:
  stage: build
  needs: ["unit-test"]
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:19.03.12
  services:
    - name: docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  # By using before_script here we override the global one as we don't need npm ;)
  before_script:
    - echo $CI_REGISTRY_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    # this two lines fix "cgroups: cgroup mountpoint does not exist: unknown"
    # job: https://gitlab.ebi.ac.uk/ensembl-apps/thr_frontend/-/jobs/741260
    # got them from: https://github.com/docker/for-linux/issues/219
    - mkdir /sys/fs/cgroup/systemd
    - mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
    # build and push
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
