image: node:14.17.3

before_script:
  # upgrade npm
  - npm install -g npm@7.11.1
  - npm -v
  - npm install

stages:
  - test
  - build


## Test

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm test

## Build

build:
  stage: build
  needs: ["test"]
  script:
    # fix: "Browserslist: caniuse-lite is outdated"
    - npx browserslist@latest --update-db
    - npm run build
