# Workflow name
name: Dependency Compatibility Check

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request (on main only) events
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on and timeout in minutes
    name: Run npm install
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - name: Check out repository code
        uses: actions/checkout@v2

      # Set up Node.js version
      - name: Set up Node.js 14.17.3
        uses: actions/setup-node@v1
        with:
          python-version: 14.17.3

      # Install dependencies and make sure there are no compatibilities issues
      - name: Install dependencies
        run: npm install

      # npm test will be added later
